name: CI

on:
  push:
  pull_request:

jobs:
  build:
    env:
      JRUBY_OPTS: '-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false'
      JAVA_OPTS: ${{ matrix.java_opts }}

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
        - mysql: 5-7
          java_opts: '-Djava.security.properties=docker/ecco-java.security' # Enable TLS 1.1, required by MySQL 5.7
        - mysql: 8-0
          java_opts: ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start MySQL container
      run: docker-compose -f docker-compose-mysql-base.yml -f docker-compose-mysql-${{ matrix.mysql }}.yml up -d

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby-9.3.4.0
        bundler-cache: true

    - name: Run tests
      run: bin/all_specs
